List<String> weightList = [
  'Ratti',
  'Gunja',
  'Masa',
  'Karsa',
  'Sukti',
  'Palam',
  'Prasrti',
  'Kudava',
  'Manika',
  'Prastha',
  'Adhaka',
  'Drona',
  'Surpa',
  'Droni',
  'Tola',
  'Vahi',
  'Khari',
  'Tula',
  'Bhara',
  'Tak',
  'Dhan',
  'Jau',
  'Siki',
  'Kancha',
  'Chhattank',
  'Seer',
  'Pav',
  'Adh-Pav',
  'Adher',
  'Ser',
  'Savaser',
  'Dhaser',
  'Paseri',
  'Adisari',
  'Bhari',
  'Daseri',
  'Pasri',
  'Maund',
  'Parmanu',
  'Marichi',
  'Tundal',
  'Yava',
  'Dhavanshi',
  'Lal sarshap',
  'Shaan',
  'kol',
  'Dhanyamash',
  'Dam'
];

List<String> sciValueList = [
  'Ounce(troy)',
  'Ounce(avdp)',
  'Pound(Troy)',
  'Pound(avdp)',
  'Pound(metric)',
  'Penny',
  'Grams',
  'Kilogram',
  'MiliGram',
  'MicroGram',
  'Megagram',
  'Slug',
  'Stone',
  'ton-assay(long)',
  'ton-assay(short)',
  'ton(long)',
  'ton(short)',
  'ton metric',
  'Hundredweight(long)',
  'Hundredweight(short)',
  'Carat',
  'Point',
  'dram(avdp)',
  'dram(troy)',
  'Grain(metric)',
  'Grain(troy)'
];

List<String> sciDesc=[
  "A troy ounce is a unit of measure used for weighing precious metals that dates back to the Middle Ages. Originally used in Troyes, France, one troy ounce is equal to 31.21 grams, according to the U.K. ... The troy ounce is often abbreviated to read 't oz' or 'oz",
  " ",
  " "
];


List<String> ayurValDesc=[
  "1 Ratti (Ratti is the seed of the 'Abrus precatorius'. It is a red seed with a black spot at one end. Abul Fazl refers to it as 'Surkh' in Ain-i-Akbari.).",
  "It is a small plant (Abrus precatorius) bearing a red and black berry. It forms the smallest of the jeweler's weights, and is considered as equal to three barleycorns.",
  "A masha is a traditional Indian unit of massIt is Type of pulse, now standardized as 0.97 grams (0.034 oz). 1 tola = 12 masha, 180 grains, or 11.6638038 grams (0.41142857 oz) P. 4.5 masha = 8 ratti or 0.97 grams considerd as 1 gram",
  "Karsa is the unit of weight roughly equal to 12 grams or 0.42 ounces.",
  "Sukti is Ayurvedic unit of measurement It is type of pearl,used to measure weight. and is equal to 24 grams or 2 Karsa",
  "Palam is Ayurvedic unit of measurement ,used to measure weight. and is equal to 48 grams or 2 sukti or 4 Karsa.",
  "Prasrti is Ayurvedic unit of measurement ,used to measure weight. and is equal to 96 grams or 4 sukti.or 2 Palam.",
  "Kudava is Ayurvedic unit of measurement Which Is corn measure of two payali ,used to measure weight. and is equal to 192 grams or 2 Prasrti,4 Palam,8 Sukti and 16 karsa.",
  "Manika is Ayurvedic unit of measurement ,used to measure weight. and is equal to 384 grams or 2 Kudava,4 Prasrti,8 Palam,16 Sukti and 32 karsa.",
  "Prastha is Ayurvedic unit of measurement ,used to measure weight. and is equal to 768 grams or 2 Manika,4 Kudava,8 Prasrti,16 Palam,32 Sukti and 64 karsa.",
  "Adhaka is Ayurvedic unit of measurement ,used to measure weight. and is equal to 3072 grams or 4 Prastha.",
  "Drona is equal to 12228 Grams and 4 Adhaka ,used to store Ghee.",
  " ",
  " ",
  "Tola equal to karsa ,1 masa and is used to measure gold and silver like metals.",
  " ",
  " ",
  " ",
  "1 bhara is equal to 96 grams and is ayurvedic weght measurement.",
  "384 rice grain or 96 dhan equal to 1 tak. and its modern equivalent is 3 grams.",
  "4 grain of rice together constitute 1 dhan. ,also it is equal to 1 wheat berry. and its modern equivalent is 0.03125 gram",
  "jau is the barley corn and was used at the time of akbar to measure weight that are small and is equal to 0.0648 grams.",
  " ",
  " ",
  "16th part of a Ser, where 1 Ser is equals to 0.9331 Kilograms",
  "1 seer is approximately equal to 1 kilogram in modern unit and it is equal to 933.1 gram and made up of 4 pav",
  "1 pav is one fourth part of 1 ser or one kilogram and is equal to 233.275 grams but in modern days it is considerd as equal to 250 grams as approx.",
  "adh-pav is actually adha pav i..e half of one pav and is equal to 116 grams approx",
  "adher means half of 1 ser and it contain 2 pav . it is modernly considerd as 500 grams as half of 1 kilogram but is acually equal to 466.55 grams",
  "1 seer is approximately equal to 1 kilogram in modern unit and it is equal to 933.1 gram and made up of 4 pav",
  "1 ser + 1 pav is equal to savaser usually in modern days considerd as 1125 grams but actually is equal to 1250 grams",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  " ",
  "Parmanu is the small unit of measuring weight in from ayurved.It consists of 1.6 grams in 1 parmanu",
  "an ancient unit used for measuring weight and its modern equivalent is 320 grams",
  " ",
  " ",
  "an ancient unit used for measuring weight and its modern equivalent is 50 grams",
  " ",
  "an ancient unit used for measuring small quantities of weight and its modern equivalent is 3 grams",
  "an ancient unit used for measuring small quantities of weight and its modern equivalent is 6 grams",
  " ",
  "The Dam was copper coin used as a weight as well as currency"
];
